### ISSUE TITLE
Error occurs when a player hits another player (both were not on the same team).

### ISSUE THREAD

**Issue by byteveil** [lewmilburn/Essence#37]
When one player hits another player, it appears that it throws an error instead of checking if `p1team` is an available argument.

```
[20:25:37 ERROR]: Could not pass event EntityDamageByEntityEvent to Essence v1.3.1
java.lang.NullPointerException: Cannot invoke "String.equalsIgnoreCase(String)" because "p1team" is null
	at net.lewmc.essence.utils.TeamUtil.areTeammates(TeamUtil.java:346) ~[essence-1.3.1.jar:?]
	at net.lewmc.essence.events.PlayerDamageEvent.onPlayerDamage(PlayerDamageEvent.java:27) ~[essence-1.3.1.jar:?]
	at com.destroystokyo.paper.event.executor.asm.generated.GeneratedEventExecutor65.execute(Unknown Source) ~[?:?]
	at org.bukkit.plugin.EventExecutor$2.execute(EventExecutor.java:77) ~[paper-api-1.20.4-R0.1-SNAPSHOT.jar:?]
	at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:81) ~[paper-api-1.20.4-R0.1-SNAPSHOT.jar:git-Paper-405]
	at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70) ~[paper-api-1.20.4-R0.1-SNAPSHOT.jar:?]
	at io.papermc.paper.plugin.manager.PaperEventManager.callEvent(PaperEventManager.java:54) ~[paper-1.20.4.jar:git-Paper-405]
	at io.papermc.paper.plugin.manager.PaperPluginManagerImpl.callEvent(PaperPluginManagerImpl.java:126) ~[paper-1.20.4.jar:git-Paper-405]
	at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:615) ~[paper-api-1.20.4-R0.1-SNAPSHOT.jar:?]
	at org.bukkit.craftbukkit.v1_20_R3.event.CraftEventFactory.callEvent(CraftEventFactory.java:265) ~[paper-1.20.4.jar:git-Paper-405]
	at org.bukkit.craftbukkit.v1_20_R3.event.CraftEventFactory.callEntityDamageEvent(CraftEventFactory.java:1252) ~[paper-1.20.4.jar:git-Paper-405]
	at org.bukkit.craftbukkit.v1_20_R3.event.CraftEventFactory.handleEntityDamageEvent(CraftEventFactory.java:1107) ~[paper-1.20.4.jar:git-Paper-405]
	at org.bukkit.craftbukkit.v1_20_R3.event.CraftEventFactory.handleEntityDamageEvent(CraftEventFactory.java:1051) ~[paper-1.20.4.jar:git-Paper-405]
	at org.bukkit.craftbukkit.v1_20_R3.event.CraftEventFactory.handleLivingEntityDamageEvent(CraftEventFactory.java:1286) ~[paper-1.20.4.jar:git-Paper-405]
	at net.minecraft.world.entity.LivingEntity.damageEntity0(LivingEntity.java:2221) ~[?:?]
	at net.minecraft.world.entity.player.Player.damageEntity0(Player.java:1059) ~[?:?]
	at net.minecraft.world.entity.LivingEntity.hurt(LivingEntity.java:1471) ~[?:?]
	at net.minecraft.world.entity.player.Player.hurt(Player.java:966) ~[?:?]
	at net.minecraft.server.level.ServerPlayer.hurt(ServerPlayer.java:1135) ~[?:?]
	at net.minecraft.world.entity.player.Player.attack(Player.java:1319) ~[?:?]
	at net.minecraft.server.level.ServerPlayer.attack(ServerPlayer.java:2283) ~[?:?]
	at net.minecraft.server.network.ServerGamePacketListenerImpl$3.a(ServerGamePacketListenerImpl.java:2769) ~[?:?]
	at net.minecraft.network.protocol.game.ServerboundInteractPacket$1.dispatch(ServerboundInteractPacket.java:24) ~[?:?]
	at net.minecraft.network.protocol.game.ServerboundInteractPacket.dispatch(ServerboundInteractPacket.java:80) ~[?:?]
	at net.minecraft.server.network.ServerGamePacketListenerImpl.handleInteract(ServerGamePacketListenerImpl.java:2693) ~[?:?]
	at net.minecraft.network.protocol.game.ServerboundInteractPacket.handle(ServerboundInteractPacket.java:67) ~[?:?]
	at net.minecraft.network.protocol.game.ServerboundInteractPacket.handle(ServerboundInteractPacket.java:12) ~[?:?]
	at net.minecraft.network.protocol.PacketUtils.lambda$ensureRunningOnSameThread$0(PacketUtils.java:54) ~[?:?]
	at net.minecraft.server.TickTask.run(TickTask.java:18) ~[paper-1.20.4.jar:git-Paper-405]
	at net.minecraft.util.thread.BlockableEventLoop.doRunTask(BlockableEventLoop.java:153) ~[?:?]
	at net.minecraft.util.thread.ReentrantBlockableEventLoop.doRunTask(ReentrantBlockableEventLoop.java:24) ~[?:?]
	at net.minecraft.server.MinecraftServer.doRunTask(MinecraftServer.java:1455) ~[paper-1.20.4.jar:git-Paper-405]
	at net.minecraft.server.MinecraftServer.d(MinecraftServer.java:194) ~[paper-1.20.4.jar:git-Paper-405]
	at net.minecraft.util.thread.BlockableEventLoop.pollTask(BlockableEventLoop.java:126) ~[?:?]
	at net.minecraft.server.MinecraftServer.pollTaskInternal(MinecraftServer.java:1432) ~[paper-1.20.4.jar:git-Paper-405]
	at net.minecraft.server.MinecraftServer.pollTask(MinecraftServer.java:1355) ~[paper-1.20.4.jar:git-Paper-405]
	at net.minecraft.util.thread.BlockableEventLoop.managedBlock(BlockableEventLoop.java:136) ~[?:?]
	at net.minecraft.server.MinecraftServer.waitUntilNextTick(MinecraftServer.java:1333) ~[paper-1.20.4.jar:git-Paper-405]
	at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1222) ~[paper-1.20.4.jar:git-Paper-405]
	at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:319) ~[paper-1.20.4.jar:git-Paper-405]
	at java.lang.Thread.run(Thread.java:840) ~[?:?]
[20:25:37 ERROR]: Could not pass event EntityDamageByEntityEvent to Essence v1.3.1
java.lang.NullPointerException: Cannot invoke "String.equalsIgnoreCase(String)" because "p1team" is null
	at net.lewmc.essence.utils.TeamUtil.areTeammates(TeamUtil.java:346) ~[essence-1.3.1.jar:?]
	at net.lewmc.essence.events.PlayerDamageEvent.onPlayerDamage(PlayerDamageEvent.java:27) ~[essence-1.3.1.jar:?]
	at com.destroystokyo.paper.event.executor.asm.generated.GeneratedEventExecutor65.execute(Unknown Source) ~[?:?]
	at org.bukkit.plugin.EventExecutor$2.execute(EventExecutor.java:77) ~[paper-api-1.20.4-R0.1-SNAPSHOT.jar:?]
	at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:81) ~[paper-api-1.20.4-R0.1-SNAPSHOT.jar:git-Paper-405]
	at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70) ~[paper-api-1.20.4-R0.1-SNAPSHOT.jar:?]
	at io.papermc.paper.plugin.manager.PaperEventManager.callEvent(PaperEventManager.java:54) ~[paper-1.20.4.jar:git-Paper-405]
	at io.papermc.paper.plugin.manager.PaperPluginManagerImpl.callEvent(PaperPluginManagerImpl.java:126) ~[paper-1.20.4.jar:git-Paper-405]
	at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:615) ~[paper-api-1.20.4-R0.1-SNAPSHOT.jar:?]
	at org.bukkit.craftbukkit.v1_20_R3.event.CraftEventFactory.callEvent(CraftEventFactory.java:265) ~[paper-1.20.4.jar:git-Paper-405]
	at org.bukkit.craftbukkit.v1_20_R3.event.CraftEventFactory.callEntityDamageEvent(CraftEventFactory.java:1252) ~[paper-1.20.4.jar:git-Paper-405]
	at org.bukkit.craftbukkit.v1_20_R3.event.CraftEventFactory.handleEntityDamageEvent(CraftEventFactory.java:1107) ~[paper-1.20.4.jar:git-Paper-405]
	at org.bukkit.craftbukkit.v1_20_R3.event.CraftEventFactory.handleEntityDamageEvent(CraftEventFactory.java:1051) ~[paper-1.20.4.jar:git-Paper-405]
	at org.bukkit.craftbukkit.v1_20_R3.event.CraftEventFactory.handleLivingEntityDamageEvent(CraftEventFactory.java:1286) ~[paper-1.20.4.jar:git-Paper-405]
	at net.minecraft.world.entity.LivingEntity.damageEntity0(LivingEntity.java:2221) ~[?:?]
	at net.minecraft.world.entity.player.Player.damageEntity0(Player.java:1059) ~[?:?]
	at net.minecraft.world.entity.LivingEntity.hurt(LivingEntity.java:1471) ~[?:?]
	at net.minecraft.world.entity.player.Player.hurt(Player.java:966) ~[?:?]
	at net.minecraft.server.level.ServerPlayer.hurt(ServerPlayer.java:1135) ~[?:?]
	at net.minecraft.world.item.enchantment.ThornsEnchantment.doPostHurt(ThornsEnchantment.java:44) ~[?:?]
	at net.minecraft.world.item.enchantment.EnchantmentHelper.lambda$doPostHurtEffects$4(EnchantmentHelper.java:164) ~[?:?]
	at net.minecraft.world.item.enchantment.EnchantmentHelper.lambda$runIterationOnItem$1(EnchantmentHelper.java:127) ~[?:?]
	at java.util.Optional.ifPresent(Optional.java:178) ~[?:?]
	at net.minecraft.world.item.enchantment.EnchantmentHelper.lambda$runIterationOnItem$1(EnchantmentHelper.java:127) ~[?:?]
	at net.minecraft.world.item.enchantment.EnchantmentHelper.runIterationOnInventory(EnchantmentHelper.java:137) ~[?:?]
	at net.minecraft.world.item.enchantment.EnchantmentHelper.doPostHurtEffects(EnchantmentHelper.java:168) ~[?:?]
	at net.minecraft.world.entity.player.Player.attack(Player.java:1400) ~[?:?]
	at net.minecraft.server.level.ServerPlayer.attack(ServerPlayer.java:2283) ~[?:?]
	at net.minecraft.server.network.ServerGamePacketListenerImpl$3.a(ServerGamePacketListenerImpl.java:2769) ~[?:?]
	at net.minecraft.network.protocol.game.ServerboundInteractPacket$1.dispatch(ServerboundInteractPacket.java:24) ~[?:?]
	at net.minecraft.network.protocol.game.ServerboundInteractPacket.dispatch(ServerboundInteractPacket.java:80) ~[?:?]
	at net.minecraft.server.network.ServerGamePacketListenerImpl.handleInteract(ServerGamePacketListenerImpl.java:2693) ~[?:?]
	at net.minecraft.network.protocol.game.ServerboundInteractPacket.handle(ServerboundInteractPacket.java:67) ~[?:?]
	at net.minecraft.network.protocol.game.ServerboundInteractPacket.handle(ServerboundInteractPacket.java:12) ~[?:?]
	at net.minecraft.network.protocol.PacketUtils.lambda$ensureRunningOnSameThread$0(PacketUtils.java:54) ~[?:?]
	at net.minecraft.server.TickTask.run(TickTask.java:18) ~[paper-1.20.4.jar:git-Paper-405]
	at net.minecraft.util.thread.BlockableEventLoop.doRunTask(BlockableEventLoop.java:153) ~[?:?]
	at net.minecraft.util.thread.ReentrantBlockableEventLoop.doRunTask(ReentrantBlockableEventLoop.java:24) ~[?:?]
	at net.minecraft.server.MinecraftServer.doRunTask(MinecraftServer.java:1455) ~[paper-1.20.4.jar:git-Paper-405]
	at net.minecraft.server.MinecraftServer.d(MinecraftServer.java:194) ~[paper-1.20.4.jar:git-Paper-405]
	at net.minecraft.util.thread.BlockableEventLoop.pollTask(BlockableEventLoop.java:126) ~[?:?]
	at net.minecraft.server.MinecraftServer.pollTaskInternal(MinecraftServer.java:1432) ~[paper-1.20.4.jar:git-Paper-405]
	at net.minecraft.server.MinecraftServer.pollTask(MinecraftServer.java:1355) ~[paper-1.20.4.jar:git-Paper-405]
	at net.minecraft.util.thread.BlockableEventLoop.managedBlock(BlockableEventLoop.java:136) ~[?:?]
	at net.minecraft.server.MinecraftServer.waitUntilNextTick(MinecraftServer.java:1333) ~[paper-1.20.4.jar:git-Paper-405]
	at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1222) ~[paper-1.20.4.jar:git-Paper-405]
	at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:319) ~[paper-1.20.4.jar:git-Paper-405]
	at java.lang.Thread.run(Thread.java:840) ~[?:?]
```

**Comment by lewmilburn** [comment]
Released hotfix https://github.com/lewmilburn/Essence/releases/tag/1.3.2
